name: 'Create tar.gz'
description: "Create a tar.gz file from the 'target' folder"

runs:
  # 'Composite Run Steps'라는 기능을 사용해 작성된 커스텀 액션이다.
  using: 'composite'

  env:
    - SCRIPT_PATH: ./.github/actions/create-tar-gz/create.sh

  steps:
    - name: 'Set execute permissions for script'
      run: chmod +x $SCRIPT_PATH
      shell: sh

    - name: 'Run tar command'
      run: $SCRIPT_PATH
      shell: sh
