# NOTE: 'Composite Run Steps'라는 기능을 사용해 작성된 커스텀 액션
name: 'Create tar.gz'
description: "Create a tar.gz file from the 'target' folder"

runs:
  using: 'composite'

  # NOTE: 여러개의 step을 실행할 수도 있다.
  steps:
    - name: 'Run tar command'
      shell: sh
      run: ./create.sh
