name: Release

on:
  push:
    tags:
      - 'release-v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create tar.gz
        run: |
          TAG_VERSION=${{ github.ref }} 
          TAG_VERSION=${TAG_VERSION#refs/tags/release-}
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV

          echo "hello_world_console_app/target/*.jar :"
          ls -l hello_world_console_app/target/*.jar
          
          echo "hello_world_console_app/target/lib :"
          ls -l hello_world_console_app/target/lib

          cd hello_world_console_app/target
          tar -czvf ../../hello_world_java-${TAG_VERSION}.tar.gz hello_world_console_app*.jar lib
          cd ../..

      - name: Read release notes
        run: |
          echo "BODY=$(cat _release-notes/${TAG_VERSION}.md)" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Create Release
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create ${{ github.ref }} \
            --title "Release ${{ env.TAG_VERSION }}" \
            --notes "${{ env.BODY }}" \
            --repo ${{ github.repository }} \
            --target ${{ github.sha }}

      - name: Upload Release Asset
        run: |
          gh release upload ${{ github.ref }} \
            ./hello_world_java-${{ env.TAG_VERSION }}.tar.gz \
            --repo ${{ github.repository }}
